export const UPDATE_FORM_FIELDS           = 'UPDATE_FORM_FIELDS';
export const UPDATE_FORM_FIELDS_END       = 'UPDATE_FORM_FIELDS_END';
export const UPDATE_SAVE_AMOUNT_START     = 'UPDATE_SAVE_AMOUNT_START';
export const UPDATE_RISK_TOLERANCE_START  = 'UPDATE_RISK_TOLERANCE_START';
export const UPDATE_FORM_FIELDS_SUCCESS   = 'UPDATE_FORM_FIELDS_SUCCESS';

export const RESET_FORM_FIELDS            = 'RESET_FORM_FIELDS';
